index:
    path: /
    defaults: { _controller: StockAdministrationBundle:Index:index }
    
login:
    path: /login
    defaults: { _controller: StockAdministrationBundle:Security:login }

login_check:
    path: /login_check
    defaults: { _controller: StockAdministrationBundle:Security:loginCheck }

logout:
    path: /logout

stock_trade:
    resource: "@StockTradeBundle/Resources/config/routing.yml"
    prefix:   /

stock_account:
    resource: "@StockAccountBundle/Resources/config/routing.yml"
    prefix:   /
