security:
    firewalls:
        login_firewall:
            pattern: ^/login$
            anonymous: ~
        secured_area:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
    
    providers:
        default_provider:
            memory:
                users:
                    admin: { password: sess2014, roles: "ROLE_ADMIN" }
                