security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: sess2014, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
<<<<<<< HEAD
            pattern:    ^/
=======
            pattern: ^/
            anonymous: ~
>>>>>>> b72a32f1acbf1c5a04244121a54e048809de32bb
            form_login:
                check_path: login_check
                login_path: login

    access_control:
<<<<<<< HEAD
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }   
=======
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    
    providers:
        default_provider:
            memory:
                users:
                    admin: { password: sess2014, roles: "ROLE_ADMIN" }
                
>>>>>>> b72a32f1acbf1c5a04244121a54e048809de32bb
