stock_account_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: StockAccountBundle:Default:index }
    methods: [GET]
    
openPersonal_page:
    path: /accounts/newperson
    defaults: {_controller: StockAccountBundle:Account:openPersonal}
    methods: [GET]
    
openPersonal_api:
    path: /accounts/newperson
    defaults: {_controller: StockAccountBundle:Account:openPersonalApi}
    methods: [POST]

openCompany_page:
    path: /accounts/newcompany
    defaults: {_controller: StockAccountBundle:Account:openCompany}
    methods: [GET]
    
openCompany_api:
    path: /accounts/newcompany
    defaults: {_controller: StockAccountBundle:Account:openCompanyApi}
    methods: [POST]
    
confirmPersonal_page:
    path: /accounts/viewperson
    defaults: {_controller: StockAccountBundle:Account:confirmPersonal}
    methods: [GET]

confirmPersonal_api:
    path: /accounts/confirmperson
    defaults: {_controller: StockAccountBundle:Account:confirmPersonalApi}
    methods: [GET]

confirmCompany_page:
    path: /accounts/viewcompany
    defaults: {_controller: StockAccountBundle:Account:confirmCompany}
    methods: [GET]
    
confirmCompany_api:
    path: /accounts/confirmcompany
    defaults: {_controller: StockAccountBundle:Account:confirmCompanyApi}
    methods: [GET]
    
reportLoss_page:
    path: /accounts/report_loss
    defaults: {_controller: StockAccountBundle:Account:reportLoss}
    methods: [GET]
    
reportLoss_api:
    path: /accounts/report_loss
    defaults: {_controller: StockAccountBundle:Account:reportLossApi}
    methods: [POST]
    
postRegister_page:
    path: /accounts/verify_renew
    defaults: {_controller: StockAccountBundle:Account:postRegister}
    methods: [GET]
    
postRegister_api:
    path: /accounts/verify_renew
    defaults: {_controller: StockAccountBundle:Account:postRegisterApi}
    methods: [POST]
    
cancel_page:
    path: /accounts/cancel
    defaults: {_controller: StockAccountBundle:Account:cancel}
    methods: [GET]
    
cancel_api:
    path: /accounts/cancel
    defaults: {_controller: StockAccountBundle:Account:cancelApi}
    methods: [POST]
    
changeInformation_api:
    path: /accounts/change
    defaults: {_controller: StockAccountBundle:Account:changeInformationApi}
    methods: [POST]
    
changeInformation_page:
    path: /accounts/change
    defaults: {_controller: StockAccountBundle:Account:changeInformation}
    methods: [GET]

viewSearch_page:
    path: /accounts/preview
    defaults: {_controller: StockAccountBundle:Account:viewSearch}
    methods: [GET]
    
viewSearch_api:
    path: /accounts/preview
    defaults: {_controller: StockAccountBundle:Account:viewSearchApi}
    methods: [POST]
    
updatePersonal_page:
    path: /accounts/updateperson
    defaults: {_controller: StockAccountBundle:Account:updatePersonal}
    methods: [GET]

changePersonal_api:
    path: /accounts/updateperson
    defaults: {_controller: StockAccountBundle:Account:changePersonalApi}
    methods: [POST]

updateCompany_page:
    path: /accounts/updatecompany
    defaults: {_controller: StockAccountBundle:Account:updateCompany}
    methods: [GET]
    
changeCompany_api:
    path: /accounts/updatecompany
    defaults: {_controller: StockAccountBundle:Account:changeCompanyApi}
    methods: [POST]