stock_account_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: StockAccountBundle:Default:index }
    
openPersonal_page:
    path: /accounts/newperson
    defaults: {_controller: StockAccountBundle:Account:openPersonal}

openCompany_page:
    path: /accounts/newcompany
    defaults: {_controller: StockAccountBundle:Account:openCompany}
    
confirmPersonal_page:
    path: /accounts/confirmperson
    defaults: {_controller: StockAccountBundle:Account:confirmPersonal}

confirmCompany_page:
    path: /accounts/confirmconpany
    defaults: {_controller: StockAccountBundle:Account:confirmCompany}
    
reportLoss_page:
    path: /accounts/report_loss
    defaults: {_controller: StockAccountBundle:Account:reportLoss}
    
postRegister_page:
    path: /accounts/verify_renew
    defaults: {_controller: StockAccountBundle:Account:postRegister}
    
cancel_page:
    path: /accounts/cancel
    defaults: {_controller: StockAccountBundle:Account:cancel}