parameters:
#    stock_account.example.class: Stock\AccountBundle\Example

services:
#    stock_account.example:
#        class: %stock_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
