deactivate_stocks:
    path: /stocks/deactivate
    defaults: { _controller: StockTradeBundle:Trade:deactivate }
    methods: [POST]
activate_stocks:
    path: /stocks/activate
    defaults: { _controller: StockTradeBundle:Trade:activate }
    methods: [POST]
trade_stocks:
    path: /stocks/trade
    defaults: { _controller: StockTradeBundle:Trade:trade }
    methods: [POST]
trade_confirm:
    path: /stocks/trade/confirm
    defaults: { _controller: StockTradeBundle:Trade:tradeConfirm }
    methods: [POST]
trade_cancel:
    path: /stocks/trade/cancel
    defaults: { _controller: StockTradeBundle:Trade:tradeCancel }
    methods: [POST]
stock_info:
    path: /stocks/info
    defaults: { _controller: StockTradeBundle:Trade:stocksInfo }
    methods: [POST]
check_account:
    path: /accounts/check
    defaults: { _controller: StockTradeBundle:Trade:checkAccount }
    methods: [POST]
addStock_page:
    path: /accounts/addstock
    defaults: {_controller: StockTradeBundle:Trade:addStockPage}
    methods: [GET]
addStock_api:
    path: /accounts/addstock
    defaults: {_controller: StockTradeBundle:Trade:addStockApi}
    methods: [POST]