parameters:
#    stock_trade.example.class: Stock\TradeBundle\Example

services:
#    stock_trade.example:
#        class: %stock_trade.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
