# src/Stock/AccountBundle/Resources/config/doctrine/LegalCustomer.orm.yml
Stock\AccountBundle\Entity\LegalCustomer:
    type: entity
    table: legal_customer
    id:
        customer_id:
            type: string
            length: 100
    fields:
        name:
            type: string
            length: 100
        legal_register_number:
            type: string
            length: 100
        id_number:
            type: string
            length: 100
        license:
            type: string
            length: 100
        executor_name:
            type: string
            length: 100
        executor_id:
            type: string
            length: 100
        executor_address:
            type: text
        executor_tel:
            type: string
            length: 20
        bank:
            type: string
            length: 100
        assests_number:
            type: string
            length: 100
        frozen:
            type: boolean