# src/Stock/AccountBundle/Resources/config/doctrine/LegalCheck.orm.yml
Stock\AccountBundle\Entity\LegalCheck:
    type: entity
    table: legal_check
    id:
        legal_register_number:
            type: string
            length: 100
    fields:
        license:
            type: string
            length: 100
        id_number:
            type: string
            length: 100
        name:
            type: string
            length: 100