# src/Stock/AccountBundle/Resources/config/doctrine/NaturalCustomer.orm.yml
Stock\AccountBundle\Entity\NaturalCustomer:
    type: entity
    table: natural_customer
    id:
        customer_id:
            type: string
            length: 100
    fields:
        name:
            type: string
            length: 100
        id_number:
            type: string
            length: 100
        register_date:
            type: date
        gender:
            type: string
            length: 100
        address:
            type: text
        occupation:
            type: text
        educational_background:
            type: text
        company_or_organization:
            type: text
        tel:
            type: string
            length: 20
        agent_id:
            type: string
            length: 100
        bank:
            type: string
            length: 100
        frozen:
            type: boolean
