Stock\TradeBundle\Entity\HoldCost:
    type: entity
    table: null
    id:
        customerId:
            type: string
            length: 255
            column: customer_id
    fields:
        holdCost:
            type: float
            column: hold_cost
        totalAmount:
            type: integer
            column: total_amount
    lifecycleCallbacks: {  }
